:PROPERTIES:
:ID:       87ce292d-af21-4d40-b07e-1e585dda0482
:END:
#+title: The Almanack of Naval Ravikant: A Guide to Wealth and Happiness
 #+date: [2022-03-26 Sat 17:01]
#+filetags: Reference
* The Almanack of Naval Ravikant: A Guide to Wealth and Happiness
* Sources::   ebook
* Author:: Eric Jorgenson
* Summary:: This book collects and curates Naval’s wisdom from Twitter, Podcasts, and Essays over the past decade. The wisdom of Naval Ravikant, created and edited by Eric Jorgenson, with Illustrations by Jack Butcher, and a Foreword by Tim Ferriss.
* Highlights::

#1
Getting rich is about knowing what to do, who to do it with, and when to do it.
2022-03-07
#2
Seek wealth, not money or status. Wealth is having assets that earn while you sleep. Money is how we transfer time and wealth. Status is your place in the social hierarchy.
2022-03-07
#3
You’re not going to get rich renting out your time. You must own equity—a piece of a business—to gain your financial freedom.
2022-03-07
#4
You will get rich by giving society what it wants but does not yet know how to get. At scale.
2022-03-07
#5
Play iterated games. All the returns in life, whether in wealth, relationships, or knowledge, come from compound interest.
2022-03-07
#6
Learn to sell. Learn to build. If you can do both, you will be unstoppable.
2022-03-07
#7
Arm yourself with specific knowledge, accountability, and leverage.
2022-03-07
#8
Specific knowledge is knowledge you cannot be trained for. If society can train you, it can train someone else and replace you.
2022-03-07
#9
Specific knowledge is found by pursuing your genuine curiosity and passion rather than whatever is hot right now.
2022-03-07
#10
Building specific knowledge will feel like play to you but will look like work to others.
2022-03-07
#11
Specific knowledge is often highly technical or creative. It cannot be outsourced or automated.
2022-03-07
#12
Embrace accountability, and take business risks under your own name. Society will reward you with responsibility, equity, and leverage.
2022-03-07
#13
Fortunes require leverage.
2022-03-07
#14
Study microeconomics, game theory, psychology, persuasion, ethics, mathematics, and computers.
2022-03-07
#15
Judgment requires experience but can be built faster by learning foundational skills.
2022-03-07
#16
Become the best in the world at what you do. Keep redefining what you do until this is true.
2022-03-07
#17
Apply specific knowledge, with leverage, and eventually you will get what you deserve.
2022-03-07
#18
Money is how we transfer wealth. Money is social credits. It is the ability to have credits and debits of other people’s time.
2022-03-07
#19
Wealth is the thing you want. Wealth is assets that earn while you sleep.
2022-03-07
#20
Technology democratizes consumption but consolidates production. The best person in the world at anything gets to do it for everyone.
2022-03-07
#21
So, technology is the set of things, as Alan Kay said, that don’t quite work yet [correction: Danny Hillis]. Once something works, it’s no longer technology.
2022-03-07
#22
if you want to be wealthy, you want to figure out which one of those things you can provide for society that it does not yet know how to get but it will want and providing it is natural to you, within your skill set, and within your capabilities. Then, you have to figure out how to scale it because if you only build one, that’s not enough.
2022-03-07
#23
figured out how to build it, and then they figured out how to scale it. [78
2022-03-07
#24
Specific knowledge cannot be taught, but it can be learned.
2022-03-07
#25
Specific knowledge is found much more by pursuing your innate talents, your genuine curiosity, and your passion.
2022-03-07
#26
“Escape competition through authenticity.” Basically, when you’re competing with people, it’s because you’re copying them. It’s because you’re trying to do the same thing. But every human is different. Don’t copy. [78]
2022-03-07
#27
The best jobs are neither decreed nor degreed. They are creative expressions of continuous learners in free markets.
2022-03-07
#28
The most important skill for getting rich is becoming a perpetual learner. You have to know how to learn anything you want to learn.
2022-03-07
#29
You really care about having studied the foundations, so you’re not scared of any book.
2022-03-07
#30
“What is the foundation required for me to learn this?” Foundations are super important. [74
2022-03-07
#31
Compound interest is a very powerful concept. Compound interest applies to more than just compounding capital.
2022-03-07
#32
Intentions don’t matter. Actions do. That’s why being ethical is hard.
2022-03-07
#33
99% of effort is wasted.
2022-03-07
#34
when it comes to the goal-oriented life, only about 1 percent of the efforts you made paid off.
2022-03-07
#35
When you’re dating, the instant you know this relationship is not going to be the one that leads to marriage, you should probably move on. When you’re studying something, like a geography or history class, and you realize you are never going to use the information, drop the class. It’s a waste of time. It’s a waste of your brain energy.
2022-03-07
#36
: when you find the 1 percent of your discipline which will not be wasted, which you’ll be able to invest in for the rest of your life and has meaning to you—go all-in and forget about the rest. [10]
2022-03-07
#37
Embrace accountability and take business risks under your own name. Society will reward you with responsibility, equity, and leverage.
2022-03-07
#38
Realize that in modern society, the downside risk is not that large.
2022-03-07
#39
. People seem to think you can create wealth—make money through work. It’s probably not going to work.
2022-03-07
#40
Without ownership, your inputs are very closely tied to your outputs.
2022-03-07
#41
Without ownership, when you’re sleeping, you’re not earning. When you’re retired, you’re not earning. When you’re on vacation, you’re not earning. And you can’t earn nonlinearly.
2022-03-07
#42
Owning equity in a company basically means you own the upside. When you own debt, you own guaranteed revenue streams and you own the downside. You want to own equity. If you don’t own equity in a business, your odds of making money are very slim.
2022-03-07
#43
If it entertains you now but will bore you someday, it’s a distraction. Keep looking.
2022-03-07
#44
I only really want to do things for their own sake.
2022-03-07
#45
The less you want something, the less you’re thinking about it, the less you’re obsessing over it, the more you’re going to do it in a natural way. The more you’re going to do it for yourself. You’re going to do it in a way you’re good at, and you’re going to stick with it. The people around you will see the quality of your work is higher. [1]
2022-03-07
#46
You’re more likely to have skills society does not yet know how to train other people to do. If someone can train other people how to do something, then they can replace you. If they can replace you, then they don’t have to pay you a lot.
2022-03-07
#47
If they can train you to do it, then eventually they will train a computer to do it.
2022-03-07
#48
Now, the problem is becoming good at whatever “it” is. It moves around from generation to generation, but a lot of it happens to be in technology.
2022-03-07
#49
One form of leverage is labor
2022-03-07
#50
would argue this is the worst form of leverage that you could possibly use. Managing other people is incredibly messy. It requires tremendous leadership skills.
2022-03-07
#51
Money is good as a form of leverage. It means every time you make a decision, you multiply it with money.
2022-03-07
#52
The final form of leverage is brand new—the most democratic form. It is: “products with no marginal cost of replication.
2022-03-07
#53
Code is probably the most powerful form of permissionless leverage.
2022-03-07
#54
Forget rich versus poor, white-collar versus blue. It’s now leveraged versus un-leveraged.
2022-03-07
#55
The most interesting and the most important form of leverage is the idea of products that have no marginal cost of replication. This is the new form of leverage.
2022-03-07
#56
Now, you can multiply your efforts without involving other humans and without needing money from other humans.
2022-03-07
#57
Probably the most interesting thing to keep in mind about new forms of leverage is they are permissionless.
2022-03-07
#58
. For labor leverage, somebody has to decide to follow you. For capital leverage, somebody has to give you money to invest or to turn into a product. Coding, writing books, recording podcasts, tweeting, YouTubing—these kinds of things are permissionless.
2022-03-07
#59
You’re never going to get rich renting out your time.
2022-03-07
#60
What you want in life is to be in control of your time.
2022-03-07
#61
Forty hour work weeks are a relic of the Industrial Age. Knowledge workers function like athletes—train and sprint, then rest and reassess.
2022-03-07
#62
If you have specific knowledge, you have accountability and you have leverage; they have to pay you what you’re worth.
2022-03-08
#63
Tools and leverage create this disconnection between inputs and outputs. The higher the creativity component of a profession, the more likely it is to have disconnected inputs and outputs.
2022-03-08
#64
If you want to be part of a great tech company, then you need to be able to SELL or BUILD. If you don’t do either, learn.
2022-03-08
#65
Earn with your mind, not your time.
2022-03-08
#66
We waste our time with short-term thinking and busywork. Warren Buffett spends a year deciding and a day acting. That act lasts decades.
2022-03-08
#67
more. Leverage magnifies those differences even more. Being at the extreme in your art is very important in the age of leverage.
2022-03-08
#68
To get rich, you need leverage. Leverage comes in labor, comes in capital, or it can come through code or media. But most of these, like labor and capital, people have to give to you. For labor, somebody has to follow you. For capital, somebody has to give you money, assets to manage, or machines. So to get these things, you have to build credibility, and you have to do it under your own name as much as possible, which is risky. So, accountability is a double-edged thing. It allows you to take credit when things go well and to bear the brunt of the failure when things go badly. [78] Clear accountability is important. Without accountability, you don’t have incentives. Without accountability, you can’t build credibility. But you take risks. You risk failure. You risk humiliation. You risk failure under your own name. Luckily, in modern society, there’s no more debtors’ prison and people aren’t imprisoned or executed for losing other people’s money, but we’re still socially hardwired to not fail in public
2022-03-08
#69
Value your time at an hourly rate, and ruthlessly spend to save time at that rate. You will never be worth more than you think you’re worth.
2022-03-08
#70
Set a very high hourly aspirational rate for yourself and stick to it. It should seem and feel absurdly high. If it doesn’t, it’s not high enough.
2022-03-08
#71
You have to get out of a relative mindset.
2022-03-08
#72
Literally, being anti-wealth will prevent you from becoming wealthy, because you will not have the right mindset for it, you
2022-03-08
#73
Be optimistic, be positive. It’s important. Optimists actually do better in the long run. 
2022-03-08
#74
One is the money game.
2022-03-08
#75
But they’re actually playing the other game,
2022-03-08
#76
Wealth creation is an evolutionarily recent positive-sum game. Status is an old zero-sum game. Those attacking wealth creation are often just seeking status.
2022-03-08
#77
Status is a zero-sum game.
2022-03-08
#78
Politics is an example of a status game.
2022-03-08
#79
The problem is, to win at a status game, you have to put somebody else down. That’s why you should avoid status games in your life—they make you into an angry, combative person.
2022-03-08
#80
Status games are always going to exist. There’s no way around it, but realize most of the time, when you’re trying to create wealth and you’re getting attacked by someone else, they’re trying to increase their own status at your expense. They’re playing a different game. And it’s a worse game. It’s a zero-sum game instead of a positive-sum game.
2022-03-08
#81
Spend more time making the big decisions. There are basically three really big decisions you make in your early life: where you live, who you’re with, and what you do.
2022-03-08
#82
Figure out what you’re good at, and start helping other people with it. Give it away. Pay it forward. Karma works because people are consistent. On a long enough timescale, you will attract what you project.
2022-03-08
#83
You’ll never be rich since you’re obviously smart, and someone will always offer you a job that’s just good enough.”
2022-03-08
#84
What you really want is freedom. You want freedom from your money problems, right? I think that’s okay. Once you can solve your money problems, either by lowering your lifestyle or by making enough money, you want to retire.
2022-03-08
#85
Retirement is when you stop sacrificing today for an imaginary tomorrow. When today is complete, in and of itself, you’re retired.
2022-03-08
#86
one way is to have so much money saved that your passive income (without you lifting a finger) covers your burn rate.
2022-03-08
#87
second is you just drive your burn rate down to zero—you become a monk.
2022-03-08
#88
A third is you’re doing something you love. You enjoy it so much, it’s not about the money. So there are multiple ways to retirement.
2022-03-08
#89
The way to get out of the competition trap is to be authentic, to find the thing you know how to do better than anybody. You know how to do it better because you love it, and no one can compete with you.
2022-03-08
#90
Lusting for money is bad for us because it is a bottomless pit. It will always occupy your mind.
2022-03-08
#91
you can hold your lifestyle fixed and hopefully make your money in giant lump sums as opposed to a trickle at a time, you won’t have time to upgrade your lifestyle.
2022-03-08
#92
I value freedom above everything else. All kinds of freedom: freedom to do what I want, freedom from things I don’t want to do, freedom from my own emotions or things that may disturb my peace. For me, freedom is my number one value.
2022-03-08
#93
The winners of any game are the people who are so addicted they continue playing even as the marginal utility from winning declines.
2022-03-08
#94
If you’re not getting promoted through the ranks, it gets a lot harder to catch up later in life. It’s good to be in a smaller company early because there’s less of an infrastructure to prevent early promotion. [76
2022-03-08
#95
blind luck where one just gets lucky because something completely out of their control happened. This includes fortune, fate, etc.
2022-03-08
#96
there’s luck through persistence, hard work, hustle, and motion.
2022-03-08
#97
third way is you become very good at spotting luck.
2022-03-08
#98
last kind of luck is the weirdest, hardest kind, where you build a unique character, a unique brand, a unique mindset, which causes luck to find you.
2022-03-08
#99
To get rich without getting lucky, we want to be deterministic.
2022-03-08
#100
build your character in a certain way, then your character becomes your destiny.
2022-03-08
#101
Your character and your reputation are things you can build, which will let you take advantage of opportunities other people may characterize as lucky, but you know it wasn’t luck. [78] My co-founder Nivi said, “In a long-term game, it seems that everybody is making each other rich. And in a short-term game, it seems like everybody is making themselves rich.”
2022-03-08
#102
if you’re building something interesting, you will always have more people who will want to know you.
2022-03-08
#103
Apply specific knowledge with leverage and eventually, you will get what you deserve.
2022-03-08
#104
The only way to truly learn something is by doing
2022-03-08
#105
What making money will do is solve your money problems. It will remove a set of things that could get in the way of being happy, but it is not going to make you happy.
2022-03-08
#106
My definition of wisdom is knowing the long-term consequences of your actions.
2022-03-08
#107
Picking the direction you’re heading in for every decision is far, far more important than how much force you apply. Just pick the right direction to start walking in, and start walking. 
2022-03-08
#108
The really smart thinkers are clear thinkers. They understand the basics at a very, very fundamental level.
2022-03-08
#109
If you can’t rederive concepts from the basics as you need them, you’re lost. You’re just memorizing. 
2022-03-08
#110
To see the truth, you have to get your ego out of the way because your ego doesn’t want to face the truth.
2022-03-08
#111
What you feel tells you nothing about the facts—it merely tells you something about your estimate of the facts.
2022-03-08
#112
A contrarian isn’t one who always objects—that’s a conformist of a different sort. A contrarian reasons independently from the ground up and resists pressure to conform.
2022-03-09
#113
Any belief you took in a package (ex. Democrat, Catholic, American) is suspect and should be re-evaluated from base principles.
2022-03-09
#114
There are two attractive lessons about suffering in the long term. It can make you accept the world the way it is. The other lesson is it can make your ego change in an extremely hard way.
2022-03-09
#115
There are no permanent solutions in a dynamic system.
2022-03-09
#116
Self-serving conclusions should have a higher bar.
2022-03-09
#117
I never ask if “I like it” or “I don’t like it.” I think “this is what it is” or “this is what it isn’t.
2022-03-09
#118
If you have a criticism of someone, then don’t criticize the person—criticize the general approach or criticize the class of activities. If you have to praise somebody, then always try and find the person who is the best example of what you’re praising and praise the person, specifically.
2022-03-09
#119
The more you know, the less you diversify.
2022-03-09
#120
During decision-making, the brain is a memory prediction machine.
2022-03-09
#121
What you want is principles. You want mental models.
2022-03-09
#122
I think a lot of modern society can be explained through evolution. One theory is civilization exists to answer the question of who gets to mate.
2022-03-09
#123
I think being successful is just about not making mistakes. It’s not about having correct judgment. It’s about avoiding incorrect judgments. 
2022-03-09
#124
Ignore the noise. The market will decide.
2022-03-09
#125
I don’t think you can be successful in business or even navigate most of our modern capitalist society without an extremely good understanding of supply-and-demand, labor-versus-capital, game theory, and those kinds of things. 
2022-03-09
#126
To me, the principal-agent problem is the single most fundamental problem in microeconomics. If you do not understand the principal-agent problem, you will not know how to navigate your way through the world.
2022-03-09
#127
if you want it done right, then you have to go yourself and do it.
2022-03-09
#128
The more closely you can tie someone’s compensation to the exact value they’re creating, the more you turn them into a principal, and the less you turn them into an agent. 
2022-03-09
#129
Compound interest—most of you should know it in the finance context.
2022-03-09
#130
In the intellectual domain, compound interest rules.
2022-03-09
#131
I think basic mathematics is really underrated. If you’re going to make money, if you’re going to invest money, your basic math should be really good.
2022-03-09
#132
But you want arithmetic, probability, and statistics. Those are extremely important.
2022-03-09
#133
Calculus is useful to know, to understand the rates of change and how nature works. But it’s more important to understand the principles of calculus—where you’re measuring the change in small discrete or small continuous events.
2022-03-09
#134
Least understood, but the most important principle for anyone claiming “science” on their side—falsifiability. If it doesn’t make falsifiable predictions, it’s not science. For you to believe something is true, it should have predictive power, and it must be falsifiable.
2022-03-09
#135
If you can’t decide, the answer is no.
2022-03-09
#136
If you cannot decide, the answer is no.
2022-03-09
#137
If you cannot decide, the answer is no. 
2022-03-09
#138
Simple heuristic: If you’re evenly split on a difficult decision, take the path more painful in the short term.
2022-03-09
#139
By definition, if the two are even and one has short-term pain, that path has long-term gain associated. With the law of compound interest, long-term gain is what you want to go toward. Your brain is overvaluing the side with the short-term happiness and trying to avoid the one with short-term pain.
2022-03-09
#140
So you generally want to lean into things with short-term pain, but long-term gain.
2022-03-09
#141
Reading science, math, and philosophy one hour per day will likely put you at the upper echelon of human success within seven years.
2022-03-09
#142
You almost have to read the stuff you’re reading, because you’re into it. You don’t need any other reason. There’s no mission here to accomplish. Just read because you enjoy it.
2022-03-09
#143
I don’t actually read a lot of books. I pick up a lot of books and only get through a few which form the foundation of my knowledge.
2022-03-09
#144
As long as I have a book in my hand, I don’t feel like I’m wasting time.
2022-03-09
#145
Explain what you learned to someone else. Teaching forces learning.
2022-03-09
#146
Read the greats in math, science, and philosophy. Ignore your contemporaries and news. Avoid tribal identification. Put truth above social approval.
2022-03-09
#147
Study logic and math, because once you’ve mastered them, you won’t fear any book.
2022-03-09
#148
Because most people are intimidated by math and can’t independently critique it, they overvalue opinions backed with math/pseudoscience.
2022-03-09
#149
. Mathematics is a solid foundation.
2022-03-09
#150
Similarly, the hard sciences are a solid foundation. Microeconomics is a solid foundation.
2022-03-09
#151
To think clearly, understand the basics. If you’re memorizing advanced concepts without being able to re-derive them as needed, you’re lost.
2022-03-09
#152
Don’t take yourself so seriously. You’re just a monkey with a plan.
2022-03-09
#153
Maybe happiness is not something you inherit or even choose, but a highly personal skill that can be learned, like fitness or nutrition.
2022-03-09
#154
Happiness is the state when nothing is missing. When nothing is missing, your mind shuts down and stops running into the past or future to regret something or to plan something.
2022-03-09
#155
To me, happiness is not about positive thoughts. It’s not about negative thoughts. It’s about the absence of desire, especially the absence of desire for external things.
2022-03-09
#156
The fewer desires I can have, the more I can accept the current state of things, the less my mind is moving, because the mind really exists in motion toward the future or the past. The more present I am, the happier and more content I will be.
2022-03-09
#157
There are no external forces affecting your emotions—as much as it may feel that way.
2022-03-09
#158
Happiness is what’s there when you remove the sense that something is missing in your life.
2022-03-09
#159
What you’re left with in that neutral state is not neutrality. I think people believe neutrality would be a very bland existence. No, this is the existence little children live. If you look at little children, on balance, they’re generally pretty happy because they are really immersed in the environment and the moment, without any thought of how it should be given their personal preferences and desires. I think the neutral state is actually a perfection state. One can be very happy as long as one isn’t too caught up in their own head. 
2022-03-09
#160
A rational person can find peace by cultivating indifference to things outside of their control.
2022-03-09
#161
Happiness, love, and passion…aren’t things you find—they’re choices you make.
2022-03-10
#162
We crave experiences that will make us be present, but the cravings themselves take us from the present moment.
2022-03-10
#163
How I combat anxiety: I don’t try and fight it, I just notice I’m anxious because of all these thoughts. I try to figure out, “Would I rather be having this thought right now, or would I rather have my peace?” Because as long as I have my thoughts, I can’t have my peace.
2022-03-10
#164
Looking outside yourself for anything is the fundamental
2022-03-10
#165
The fundamental delusion: There is something out there that will make me happy and fulfilled forever.
2022-03-10
#166
Desire is a contract you make with yourself to be unhappy until you get what you want.
2022-03-10
#167
Desire is a contract you make with yourself to be unhappy until you get what you want.
2022-03-10
#168
, that happiness is internal. That conclusion set me on a path of working more on my internal self and realizing all real success is internal and has very little to do with external circumstances.
2022-03-10
#169
Survival and replication drive put us on the work treadmill. Hedonic adaptation keeps us there. The trick is knowing when to jump off and play instead.
2022-03-10
#170
the real winners are the ones who step out of the game entirely, who don’t even play the game, who rise above it. Those are the people who have such internal mental and self-control and self-awareness, they need nothing from anybody else.
2022-03-10
#171
You can get almost anything you want out of life, as long as it’s one thing and you want it far more than anything else.
2022-03-10
#172
Peace is happiness at rest, and happiness is peace in motion. You can convert peace into happiness anytime you want. But peace is what you want most of the time. If you’re a peaceful person, anything you do will be a happy activity.
2022-03-10
#173
The enemy of peace of mind is expectations drilled into you by society and other people.
2022-03-10
#174
The reality is life is a single-player game. You’re born alone. You’re going to die alone.
2022-03-10
#175
You’re gone in three generations, and nobody cares.
2022-03-10
#176
Perhaps one reason why yoga and meditation are hard to sustain is they have no extrinsic value. Purely single-player games.
2022-03-10
#177
It’s such a poisonous emotion because, at the end of the day, you’re no better off with jealousy. You’re unhappier, and the person you’re jealous of is still successful or good-looking or whatever they are.
2022-03-10
#178
If you’re not willing to do a wholesale, 24/7, 100 percent swap with who that person is, then there is no point in being jealous. Once I came to that realization, jealousy faded away because I don’t want to be anybody else. I’m perfectly happy being me. By the way, even that is under my control. To be happy being me. It’s just there are no social rewards for it.
2022-03-10
#179
My most surprising discovery in the last five years is that peace and happiness are skills.
2022-03-10
#180
When working, surround yourself with people more successful than you.
2022-03-10
#181
When playing, surround yourself with people happier than you.
2022-03-10
#182
It’s all trial and error. You just see what works. You can try sitting meditation.
2022-03-10
#183
The most important trick to being happy is to realize happiness is a skill you develop and a choice you make.
2022-03-10
#184
The obvious one is meditation—insight meditation. Working toward a specific purpose on it, which is to try and understand how my mind works.
2022-03-10
#185
Every time you catch yourself desiring something, say, “Is it so important to me I’ll be unhappy unless this goes my way?” You’re going to find with the vast majority of things it’s just not
2022-03-10
#186
The more you judge, the more you separate yourself.
2022-03-10
#187
Caught in a funk? Use meditation, music, and exercise to reset your mood. Then choose a new path to commit emotional energy for rest of
2022-03-10
#188
Politics, academia, and social status are all zero-sum games. Positive-sum games create positive people.
2022-03-11
#189
Increase serotonin in the brain without drugs: Sunlight, exercise, positive thinking, and tryptophan.
2022-03-11
#190
Your life is a firefly blink in a night. You’re here for such a brief period of time. If you fully acknowledge the futility of what you’re doing, then I think it can bring great happiness and peace because you realize this is a game. But it’s a fun game. All that matters is you experience your reality as you go through life.
2022-03-11
#191
You’re going to die one day, and none of this is going to matter. So enjoy yourself. Do something positive. Project some love. Make someone happy. Laugh a little bit. Appreciate the moment. And do your work. 
2022-03-11
#192
All you should do is what you want to do.
2022-03-14
#193
To make an original contribution, you have to be irrationally obsessed with something.
2022-03-14
#194
Sugar makes you hungry. Sugar signals to your body, “There’s this incredible food resource in the environment we’re not evolved for,” so you rush out to get sugar. The problem is the sugar effect dominates the fat effect. If you eat a fatty meal and you throw some sugar in, the sugar is going to deliver hunger and fat is going to deliver the calories and you’re just going to binge. That’s why all desserts are large combinations of fat and carbs together.
2022-03-14
#195
In nature, it’s very rare to find carbs and fat together. In nature, I find carbs and fat together in coconuts, in mangoes, maybe in bananas, but it’s basically tropical fruits. The combination of sugar and fat together is really deadly.
2022-03-14
#196
Dietary fat drives satiety. Dietary sugar drives hunger. The sugar effect dominates. Control your appetite accordingly.
2022-03-14
#197
The harder the workout, the easier the day.
2022-03-14
#198
World’s simplest diet: The more processed the food, the less one should consume.
2022-03-14
#199
What I did was decide my number one priority in life, above my happiness, above my family, above my work, is my own health. It starts with my physical health. [4] Because my physical health became my number one priority, then I could never say I don’t have time. In the morning, I work out, and however long it takes is how long it takes. I do not start my day until I’ve worked out. I don’t care if the world is imploding and melting down, it can wait another thirty minutes until I’m done working out.
2022-03-14
#200
If something is your number one priority, then you will do it. That’s just the way life works. If you’ve got a fuzzy basket of ten or fifteen
2022-03-14
#201
Basically, if you are making the hard choices right now in what to eat, you’re not eating all the junk food you want, and making the hard choice to work out. So, your life long-term will be easy.
2022-03-14
#202
If you make the easy choices right now, your overall life will be a lot harder. 
2022-03-14
#203
Your breath is one of the few places where your autonomic nervous system meets your voluntary nervous system. It’s involuntary, but you can also control it.
2022-03-14
#204
Our bodies have lost touch with the cold. The cold is important because it can activate the immune system.
2022-03-14
#205
Meditation is intermittent fasting for the mind. Too much sugar leads to a heavy body, and too many distractions lead to a heavy mind. Time spent undistracted and alone, in self-examination, journaling, meditation, resolves the unresolved and takes us from mentally fat to fit.
2022-03-14
#206
Life-hack: When in bed, meditate. Either you will have a deep meditation or fall asleep. Victory either way.
2022-03-14
#207
Insight meditation lets you run your brain in debug mode until you realize you’re just a subroutine in a larger program.
2022-03-18
#208
The ability to singularly focus is related to the ability to lose yourself and be present, happy, and (ironically) more effective. 
2022-03-18
#209
To have peace of mind, you have to have peace of body first.
2022-03-18
#210
Impatience with actions, patience with results.
2022-03-18
#211
Anything you have to do, just get it done.
2022-03-18
#212
you just have to be patient with the results because you’re dealing with complex systems and many people.
2022-03-18
#213
The current environment programs the brain, but the clever brain can choose its upcoming environment.
2022-03-18
#214
Number one: read.
2022-03-18
#215
Related to the skill of reading are the skills of mathematics and persuasion.
2022-03-18
#216
Mathematics helps with all the complex and difficult things in life.
2022-03-18
#217
Nature speaks in mathematics.
2022-03-18
#218
The hardest thing is not doing what you want—it’s knowing what you want.
2022-03-18
#219
Advice to my younger self: “Be exactly who you are.
2022-03-18
#220
Holding back means staying in bad relationships and bad jobs for years instead of minutes.
2022-03-18
#221
Courage isn’t charging into a machine gun nest. Courage is not caring what other people think.
2022-03-18
#222
Value your time. It is all you have. It’s more important than your money. It’s more important than your friends. It is more important than anything. Your time is all you have. Do not waste your time.
2022-03-18
#223
anger is a loss of control over the situation. Anger is a contract you make with yourself to be in physical and mental and emotional turmoil until reality changes.
2022-03-18
#224
It’s personal. You have to find your own meaning.
2022-03-19
#225
There is no meaning to life.
2022-03-19
#226
Anything you do will fade.
2022-03-19
#227
There is no fundamental, intrinsic purposeful meaning to the Universe.
2022-03-19
#228
Basically, in physics, the arrow of time comes from entropy. The second law of thermodynamics states entropy only goes up, which means disorder in the Universe only goes up, which means concentrated free energy only goes down.
2022-03-19
#229
. The more complex system you create, whether it’s through computers, civilization, art, mathematics, or creating a family—you actually accelerate the heat death of the Universe. You’re pushing us towards this point where we end up as one thing.
2022-03-19
#230
Honesty is a core, core, core value. By honesty, I mean I want to be able to just be me. I never want to be in an environment or around people where I have to watch what I say.
2022-03-19
#231
Before you can lie to another, you must first lie to yourself.
2022-03-19
#232
Another example of a foundational value: I don’t believe in any short-term thinking or dealing.
2022-03-19
#233
Another one is I only believe in peer relationships.
2022-03-19
#234
Another: I don’t believe in anger anymore.
2022-03-19
#235
Anger is a hot coal you hold in your hand while waiting to throw it at somebody.
2022-03-19
#236
All benefits in life come from compound interest, whether in money, relationships, love, health, activities, or habits. I only want to be around people I know I’m going to be around for the rest of my life. I only want to work on things I know have long-term payout.
2022-03-23
#237
The older the question, the older the answers.
2022-03-23
#238
Understanding the long-term consequences of your actions. 
2022-03-23
#239
the only thing that exists is this exact point where you are in space at the exact time you happen to be here.
2022-03-23 
